### ISSUE TITLE
BUG: Moving of node causes rendering error

### ISSUE THREAD

**Issue by rolandschuetz** [betterembed/neos-embed#12]
**Describe the bug**
I created a BetterEmbed content NodeType and published it. Then I moved it to another page and gets rendered with the warning "Please enter a URL", this is only fixed after changing the url.

**To Reproduce**
See above.

**Expected behavior**
Rendering as before

**Comment by davidspiola** [comment]
Thx Roland! I‘ll check it in the next few days.

**Comment by Grienauer** [comment]
Merge requests are also very welcome! ;)

**Comment by davidspiola** [comment]
I think this is related to #17, which I have already fixed in the master branch. Let's check again when the release is ready to make sure it works

**Comment by rolandschuetz** [comment]
Perfect, works :)
