### ISSUE TITLE
BUG: Schemas not matching

### ISSUE THREAD

**Issue by rolandschuetz** [betterembed/neos-embed#15]
**Describe the bug**
The schemas in YAML and PHP are not matching:

- YAML uses thumbnailSrc https://github.com/betterembed/neos-betterembed/blob/master/Configuration/NodeTypes.BetterEmbed.Record.yaml
 - Dto has no property https://github.com/betterembed/neos-betterembed/blob/master/Classes/Domain/Dto/BetterEmbedRecord.php#L40
 - EmbedService uses thumbail https://github.com/betterembed/neos-betterembed/blob/master/Classes/Service/EmbedService.php#L203

**Comment by davidspiola** [comment]
fixed
