### ISSUE TITLE
BUG: Urls with GET-Parameters are not correctly supported

### ISSUE THREAD

**Issue by rolandschuetz** [betterembed/neos-embed#16]
**Describe the bug**
While a preview for https://youtu.be/QL9UMMzyFFI is correctly rendered, the same video included with the url https://www.youtube.com/watch?v=QL9UMMzyFFI is not correctly shown.

**To Reproduce**
Try above urls.

**Expected behavior**
Url with GET-Parameters should show a correct image.

**Comment by Grienauer** [comment]
this does not seem to be an API bug.
if you test the API here: https://api.betterembed.com/swagger/index.html the output is correct.

**Comment by rolandschuetz** [comment]
It's not an API bug, it's a neos integration bug. I already took a look with David and he has some ideas why this is not working.

**Comment by davidspiola** [comment]
@rolandschuetz I tested it again, and it works as expected. Can you pls check one more time and let me know. If yes, let's take a look together

**Comment by rolandschuetz** [comment]
@davidspiola Above URL still does not work and cause the following error _Youtube URLs are not supported due GDPR consent gateway protection._

I guess this is by design, but I don't understand the error. Especially, why does https://youtu.be/QL9UMMzyFFI still work, if it's about GDPR?
