### ISSUE TITLE
BUG: Deleting a content element should not (always) delete the record

### ISSUE THREAD

**Issue by rolandschuetz** [betterembed/neos-embed#17]
**Describe the bug**
deleting one content item causes the document record to be deleted, even when in use.

**To Reproduce**
1. Create two content elements with the same url and publish them.
2. Delete one of the content elements
3. Now the other element shows "Bitte geben Sie eine URL im Inspektor-Panel ein."

**Expected behavior**
The document record should exist until the reference will be deleted.

**Comment by davidspiola** [comment]
fixed in next release
