### ISSUE TITLE
FEATURE: BetterEmbed downloads the same source multiple times

### ISSUE THREAD

**Issue by rolandschuetz** [betterembed/neos-embed#18]
Multiple Content Items with the same link should not download the image.

**To Reproduce**
1. Create a content item with a url (now in the media browser you see the new preview image)
2. Delete the item
3. Create a new item with the same url

Now the same image exists twice in the media browser. It would be great to have the same resource only once in the media browser.

**Comment by davidspiola** [comment]
fixed in next release
